/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import BD.Canciones;
import BD.ListasRep;
import Controller.Controller;
import Model.Model;
import com.sun.tools.javac.Main;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowStateListener;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author ruben
 */
public class crearPlayList extends javax.swing.JInternalFrame {

    MainUI ui;


    /**
     * Creates new form crearPlayList
     */
    public crearPlayList(MainUI ui) {
        this.ui = ui;
        initComponents();
    }

    Model model = new Model();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createplayListField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        playListsTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        songTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        playListTable = new javax.swing.JTable();
        changePlayListNameButton = new javax.swing.JButton();
        createPlayListButton = new javax.swing.JButton();
        addSongButton = new javax.swing.JButton();
        removeSongButton = new javax.swing.JButton();
        deletePlayListButton = new javax.swing.JButton();
        cancionesTableText = new javax.swing.JLabel();
        playListTableText = new javax.swing.JLabel();
        playListShowTableText = new javax.swing.JLabel();
        playListNameText = new javax.swing.JLabel();
        logoDecoracionCrearListas = new javax.swing.JLabel();
        bgCreatePlayList = new javax.swing.JLabel();
        searchPlayListButton = new javax.swing.JButton();

        setBorder(null);
        this.setResizable(false);
        this.setClosable(false);
        this.setIconifiable(false);
        this.setMaximizable(false);

        playListsTable.setBackground(new java.awt.Color(77, 133, 77));
        playListTable.setBackground(new java.awt.Color(77, 133, 77));
        songTable.setBackground(new java.awt.Color(77, 133, 77));
        playListsTable.setFillsViewportHeight(true);
        playListTable.setFillsViewportHeight(true);
        songTable.setFillsViewportHeight(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createplayListField.setBackground(new java.awt.Color(0, 0, 0));
        createplayListField.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        createplayListField.setForeground(new java.awt.Color(255, 255, 255));
        createplayListField.setText("Rock");
        createplayListField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 102)));
        createplayListField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createplayListFieldActionPerformed(evt);
            }
        });
        jPanel1.add(createplayListField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 340, 60));

        playListsTable.setModel(new javax.swing.table.DefaultTableModel(
        ));
        jScrollPane2.setViewportView(playListsTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 970, 150));

        songTable.setModel(new javax.swing.table.DefaultTableModel(
        ));
        jScrollPane1.setViewportView(songTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 970, 270));

        playListTable.setModel(new javax.swing.table.DefaultTableModel(
        ));
        jScrollPane3.setViewportView(playListTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 970, 270));

        changePlayListNameButton.setBackground(new java.awt.Color(0, 0, 0));
        changePlayListNameButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        changePlayListNameButton.setForeground(new java.awt.Color(255, 255, 255));
        changePlayListNameButton.setText("Cambiar Nombre");
        changePlayListNameButton.setToolTipText("");
        changePlayListNameButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 51)));
        changePlayListNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePlayListNameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changePlayListNameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 240, 60));

        createPlayListButton.setBackground(new java.awt.Color(0, 0, 0));
        createPlayListButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        createPlayListButton.setForeground(new java.awt.Color(255, 255, 255));
        createPlayListButton.setText("Crear PlayList");
        createPlayListButton.setToolTipText("");
        createPlayListButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 51)));
        jPanel1.add(createPlayListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 840, 240, 60));
        createPlayListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlayListButtonActionPerformed(evt);
            }
        });

        searchPlayListButton.setBackground(new java.awt.Color(0, 0, 0));
        searchPlayListButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        searchPlayListButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPlayListButton.setText("Buscar PlayList");
        searchPlayListButton.setToolTipText("");
        searchPlayListButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 51)));
        jPanel1.add(searchPlayListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 770, 240, 60));
        searchPlayListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPlayListButtonActionPerformed(evt);
            }
        });

        addSongButton.setBackground(new java.awt.Color(0, 0, 0));
        addSongButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        addSongButton.setForeground(new java.awt.Color(255, 255, 255));
        addSongButton.setText("Añadir Canción");
        addSongButton.setToolTipText("");
        addSongButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 51)));
        jPanel1.add(addSongButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 840, 240, 60));
        addSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongButtonActionPerformed(evt);
            }
        });

        removeSongButton.setBackground(new java.awt.Color(0, 0, 0));
        removeSongButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        removeSongButton.setForeground(new java.awt.Color(255, 255, 255));
        removeSongButton.setText("Quitar Canción");
        removeSongButton.setToolTipText("");
        removeSongButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 51)));
        removeSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSongButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeSongButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 770, 240, 60));

        deletePlayListButton.setBackground(new java.awt.Color(0, 0, 0));
        deletePlayListButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        deletePlayListButton.setForeground(new java.awt.Color(255, 255, 255));
        deletePlayListButton.setText("Borrar PlayList");
        deletePlayListButton.setToolTipText("");
        deletePlayListButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 51)));
        deletePlayListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlayListButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletePlayListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 240, 60));

        cancionesTableText.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        cancionesTableText.setForeground(new java.awt.Color(255, 255, 255));
        cancionesTableText.setText("Canciones:");
        jPanel1.add(cancionesTableText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 290, 40));

        playListTableText.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        playListTableText.setForeground(new java.awt.Color(255, 255, 255));
        playListTableText.setText("PlayLists:");
        jPanel1.add(playListTableText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 290, 40));

        playListShowTableText.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        playListShowTableText.setForeground(new java.awt.Color(255, 255, 255));
        playListShowTableText.setText("PlayList:");
        jPanel1.add(playListShowTableText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 290, 40));

        playListNameText.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        playListNameText.setForeground(new java.awt.Color(255, 255, 255));
        playListNameText.setText("Nombre la PlayList:");
        jPanel1.add(playListNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 290, 40));

        logoDecoracionCrearListas.setIcon(new javax.swing.ImageIcon("src/main/java/Img/spochofyLogoGrande.png")); // NOI18N
        jPanel1.add(logoDecoracionCrearListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 570, 460));

        bgCreatePlayList.setIcon(new javax.swing.ImageIcon("src/main/java/Img/background.png")); // NOI18N
        jPanel1.add(bgCreatePlayList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 960));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createplayListFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createplayListFieldActionPerformed
    }//GEN-LAST:event_createplayListFieldActionPerformed

    private void changePlayListNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePlayListNameButtonActionPerformed
        int row = playListsTable.getSelectedRow();
        Controller.updatePlaylistName(ui, row, createplayListField.getText());
    }//GEN-LAST:event_changePlayListNameButtonActionPerformed
    private void createPlayListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePlayListNameButtonActionPerformed
        Controller.createPlaylist(ui, createplayListField.getText());
        System.out.println(createplayListField.getText());
    }//GEN-LAST:event_changePlayListNameButtonActionPerformed

    private void removeSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSongButtonActionPerformed
        int row = (int) playListsTable.getValueAt(playListsTable.getSelectedRow(),0);
        int song = (int) playListTable.getValueAt(playListTable.getSelectedRow(), 0);
        Controller.removeSongFromPlaylist(ui, row, song);
    }//GEN-LAST:event_removeSongButtonActionPerformed
    private void addSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSongButtonActionPerformed
        int row = (int) playListsTable.getValueAt(playListsTable.getSelectedRow(),0);
        int song = (int) songTable.getValueAt(songTable.getSelectedRow(), 0);
        Controller.addSongToPlaylist(ui,row,song);
    }//GEN-LAST:event_removeSongButtonActionPerformed
    private void searchPlayListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSongButtonActionPerformed
        int row = (int) playListsTable.getValueAt(playListsTable.getSelectedRow(),0);
        Controller.selectPlaylist(ui, row);
    }//GEN-LAST:event_removeSongButtonActionPerformed

    private void deletePlayListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlayListButtonActionPerformed
        int row = (int) playListsTable.getValueAt(playListsTable.getSelectedRow(),0);
        Controller.deletePlaylist(ui,row);
    }//GEN-LAST:event_deletePlayListButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSongButton;
    private javax.swing.JLabel bgCreatePlayList;
    private javax.swing.JLabel cancionesTableText;
    private javax.swing.JButton changePlayListNameButton;
    private javax.swing.JButton createPlayListButton;
    private javax.swing.JTextField createplayListField;
    private javax.swing.JButton deletePlayListButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoDecoracionCrearListas;
    private javax.swing.JLabel playListNameText;
    private javax.swing.JLabel playListShowTableText;
    public javax.swing.JTable playListTable;
    private javax.swing.JLabel playListTableText;
    public javax.swing.JTable playListsTable;
    private javax.swing.JButton removeSongButton;
    public javax.swing.JTable songTable;
    private javax.swing.JButton searchPlayListButton;
    // End of variables declaration//GEN-END:variables
}
