/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.Controller;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ruben
 */
public class ListasUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form listasUI
     */
    public ListasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        stopButton = new JButton();
        playButton = new JButton();
        jScrollPane1 = new JScrollPane();
        tablaListas = new JTable();
        titleListas = new JLabel();
        logoDecoracionListas = new JLabel();
        bgListas = new JLabel();

        setBorder(null);
        this.setResizable(false);
        this.setClosable(false);
        this.setIconifiable(false);
        this.setMaximizable(false);

        jPanel1.setLayout(new AbsoluteLayout());

        stopButton.setIcon(new ImageIcon("src/main/java/Img/stopButton.png")); // NOI18N
        stopButton.setContentAreaFilled(false);
        jPanel1.add(stopButton, new AbsoluteConstraints(410, 780, 80, 80));
        stopButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        playButton.setIcon(new ImageIcon("src/main/java/Img/playButton.png")); // NOI18N
        playButton.setToolTipText("");
        playButton.setContentAreaFilled(false);
        jPanel1.add(playButton, new AbsoluteConstraints(290, 780, 80, 80));
        playButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        tablaListas.setBackground(new Color(77, 133, 77));
        tablaListas.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));

        tablaListas.setFillsViewportHeight(true);
        tablaListas.setFont(new Font("Gotham", Font.BOLD, 16));

        tablaListas.setGridColor(new Color(0, 51, 51));
        tablaListas.setSelectionBackground(new Color(33, 100, 10));
        jScrollPane1.setViewportView(tablaListas);

        jPanel1.add(jScrollPane1, new AbsoluteConstraints(820, 20, 1070, 880));

        titleListas.setFont(new Font("Gotham", 1, 36)); // NOI18N
        titleListas.setForeground(new Color(255, 255, 255));
        jPanel1.add(titleListas, new AbsoluteConstraints(30, 20, 770, 80));

        logoDecoracionListas.setIcon(new ImageIcon("src/main/java/Img/spochofyLogoGrande.png")); // NOI18N
        jPanel1.add(logoDecoracionListas, new AbsoluteConstraints(190, 210, 510, 420));

        bgListas.setIcon(new ImageIcon("src/main/java/Img/background.png")); // NOI18N
        jPanel1.add(bgListas, new AbsoluteConstraints(0, 0, 1910, 920));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        int lid = (int) tablaListas.getValueAt(tablaListas.getSelectedRow(),0);
        Controller.playMusic(lid);
    }//GEN-LAST:event_playButtonActionPerformed
    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        Controller.stopMusic();
    }//GEN-LAST:event_playButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgListas;
    private javax.swing.JLabel logoDecoracionListas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaListas;
    public javax.swing.JButton playButton;
    public javax.swing.JButton stopButton;
    public javax.swing.JLabel titleListas;
    // End of variables declaration//GEN-END:variables
}
