/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

/**
 *
 * @author dam1
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        pwdTextLabel = new javax.swing.JLabel();
        pwdField = new javax.swing.JTextField();
        loginField = new javax.swing.JTextField();
        loginTextLabel = new javax.swing.JLabel();
        loginBackground = new javax.swing.JLabel();

        setBorder(null);

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pwdTextLabel.setFont(new java.awt.Font("Gotham Light", 1, 24)); // NOI18N
        pwdTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        pwdTextLabel.setText("PASSWORD:");
        loginPanel.add(pwdTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 40));

        pwdField.setBackground(new java.awt.Color(0, 0, 0));
        pwdField.setFont(new java.awt.Font("Gotham Light", 1, 24)); // NOI18N
        pwdField.setForeground(new java.awt.Color(255, 255, 255));
        pwdField.setText("jTextField1");
        pwdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        loginPanel.add(pwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 40));

        loginField.setBackground(new java.awt.Color(0, 0, 0));
        loginField.setFont(new java.awt.Font("Gotham Light", 1, 24)); // NOI18N
        loginField.setForeground(new java.awt.Color(255, 255, 255));
        loginField.setText("jTextField1");
        loginField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        loginPanel.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 290, 40));

        loginTextLabel.setFont(new java.awt.Font("Gotham Light", 1, 24)); // NOI18N
        loginTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginTextLabel.setText("USER:");
        loginPanel.add(loginTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, 40));

        loginBackground.setIcon(new javax.swing.ImageIcon("src/main/java/Img/background.png")); // NOI18N
        loginPanel.add(loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginBackground;
    private javax.swing.JTextField loginField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTextLabel;
    private javax.swing.JTextField pwdField;
    private javax.swing.JLabel pwdTextLabel;
    // End of variables declaration//GEN-END:variables
}
