/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Temporal.Controller;
import com.sun.tools.javac.Main;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author dam1
 */
public class Login extends javax.swing.JInternalFrame {


    MainUI ui;
    /**
     * Creates new form Login
     */
    public Login(MainUI ui) {
        this.ui = ui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        pwdTextLabel = new javax.swing.JLabel();
        loginpwdField = new javax.swing.JPasswordField();
        loginField = new javax.swing.JTextField();
        loginTextLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        logInButton = new javax.swing.JButton();
        loginBackground = new javax.swing.JLabel();

        setBorder(null);

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pwdTextLabel.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        pwdTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        pwdTextLabel.setText("CONTRASEÑA:");
        loginPanel.add(pwdTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 40));

        loginpwdField.setBackground(new java.awt.Color(0, 0, 0));
        loginpwdField.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        loginpwdField.setForeground(new java.awt.Color(153, 153, 153));
        loginpwdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        loginpwdField.setBorder(BorderFactory.createCompoundBorder(
                loginpwdField.getBorder(), BorderFactory.createEmptyBorder(0, 10, 0, 0)
        ));
        loginpwdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginpwdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginpwdFieldFocusLost(evt);
            }
        });
        loginPanel.add(loginpwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 40));

        loginField.setBackground(new java.awt.Color(0, 0, 0));
        loginField.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        loginField.setForeground(new java.awt.Color(153, 153, 153));
        loginField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        loginField.setBorder(BorderFactory.createCompoundBorder(
                loginField.getBorder(), BorderFactory.createEmptyBorder(0, 10, 0, 0)
        ));
        loginField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFieldFocusLost(evt);
            }
        });
        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        loginPanel.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 290, 40));

        loginTextLabel.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        loginTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginTextLabel.setText("USUARIO:");
        loginPanel.add(loginTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 40));

        signInButton.setBackground(new java.awt.Color(0, 0, 0));
        signInButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("SIGN IN");
        signInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        loginPanel.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, 40));

        logInButton.setBackground(new java.awt.Color(0, 0, 0));
        logInButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        logInButton.setForeground(new java.awt.Color(255, 255, 255));
        logInButton.setText("LOG IN");
        logInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        loginPanel.add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 110, 40));

        loginBackground.setIcon(new javax.swing.ImageIcon("src/main/java/Img/background.png")); // NOI18N
        loginPanel.add(loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void loginFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFieldFocusGained
        if(loginField.getText().equals("Usuario")){
            loginField.setText("");
            loginField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_loginFieldFocusGained

    private void loginFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFieldFocusLost
        if(loginField.getText().equals("")){
            loginField.setText("Usuario");
            loginField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_loginFieldFocusLost

    private void loginpwdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginpwdFieldFocusGained

    }//GEN-LAST:event_loginpwdFieldFocusGained

    private void loginpwdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginpwdFieldFocusLost

    }//GEN-LAST:event_loginpwdFieldFocusLost

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        Controller.singin(ui);
    }//GEN-LAST:event_signInButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel loginBackground;
    private javax.swing.JTextField loginField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTextLabel;
    private javax.swing.JPasswordField loginpwdField;
    private javax.swing.JLabel pwdTextLabel;
    private javax.swing.JButton signInButton;
    // End of variables declaration//GEN-END:variables
}
