/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.Controller;

import javax.swing.*;
import java.awt.Color;

/**
 *
 * @author dam1
 */
public class Sign extends javax.swing.JInternalFrame {

    MainUI ui;

    /**
     * Creates new form Login
     */
    public Sign() {
        this.ui = ui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        signpwdTextLabel = new javax.swing.JLabel();
        signpwdField = new javax.swing.JPasswordField();
        signinField = new javax.swing.JTextField();
        signinTextLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        signinBackground = new javax.swing.JLabel();

        setBorder(null);

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signpwdTextLabel.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        signpwdTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        signpwdTextLabel.setText("CONTRASEÑA:");
        loginPanel.add(signpwdTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 40));

        signpwdField.setBackground(new java.awt.Color(0, 0, 0));
        signpwdField.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        signpwdField.setForeground(new java.awt.Color(153, 153, 153));
        signpwdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        signpwdField.setBorder(BorderFactory.createCompoundBorder(
                signpwdField.getBorder(), BorderFactory.createEmptyBorder(0, 10, 0, 0)
        ));
        signpwdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signpwdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signpwdFieldFocusLost(evt);
            }
        });
        loginPanel.add(signpwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 40));

        signinField.setBackground(new java.awt.Color(0, 0, 0));
        signinField.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        signinField.setForeground(new java.awt.Color(153, 153, 153));
        signinField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        signinField.setBorder(BorderFactory.createCompoundBorder(
                signinField.getBorder(), BorderFactory.createEmptyBorder(0, 10, 0, 0)
        ));
        signinField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signinFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signinFieldFocusLost(evt);
            }
        });
        signinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinFieldActionPerformed(evt);
            }
        });
        loginPanel.add(signinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 290, 40));

        signinTextLabel.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        signinTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        signinTextLabel.setText("USUARIO:");
        loginPanel.add(signinTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 40));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("VOLVER");
        cancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        loginPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, 40));

        signInButton.setBackground(new java.awt.Color(0, 0, 0));
        signInButton.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("SIGN IN");
        signInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 51, 51)));
        loginPanel.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 110, 40));

        signinBackground.setIcon(new javax.swing.ImageIcon("src/main/java/Img/background.png")); // NOI18N
        loginPanel.add(signinBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinFieldActionPerformed

    private void signinFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signinFieldFocusGained
        if(signinField.getText().equals("Usuario")){
            signinField.setText("");
            signinField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_signinFieldFocusGained

    private void signinFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signinFieldFocusLost
        if(signinField.getText().equals("")){
            signinField.setText("Usuario");
            signinField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_signinFieldFocusLost

    private void signpwdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signpwdFieldFocusGained

    }//GEN-LAST:event_signpwdFieldFocusGained

    private void signpwdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signpwdFieldFocusLost

    }//GEN-LAST:event_signpwdFieldFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Controller.openLogin(ui);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel signinBackground;
    private javax.swing.JTextField signinField;
    private javax.swing.JLabel signinTextLabel;
    private javax.swing.JPasswordField signpwdField;
    private javax.swing.JLabel signpwdTextLabel;
    // End of variables declaration//GEN-END:variables
}
